# All rules: https://github.com/DavidAnson/markdownlint#rules--aliases
default: true  # Default state for all rules
MD013: false  # line-length: We don't fill paragaraphs/limit line length
MD034: false  # no-bare-urls - We use pymdownx.magiclink which allows bare urls
MD046: false  # code-block-style - This doesn't play well with material's admonitions)
2023/8/13
